import datetime
import pyarrow
import typing

from bauplan._internal.schema import (
    Branch, Commit, Job, JobContext, JobKind, JobLogList, JobState,
    Namespace, Ref, Table, Tag,
)
from bauplan._internal.state import (
    ExternalTableCreateState, RunState,
    TableCreatePlanApplyState, TableCreationPlanState,
    TableDataImportState,
)

class Client:
    def __init__(cls, /, profile: str | None = None, api_key: str | None = None, client_timeout: int | None = None, config_file_path: str | None = None) -> None: ...
    def apply_table_creation_plan(self, /, plan: TableCreationPlanState | str, *, args: dict[str, str] | None = None, priority: int | None = None, client_timeout: int | None = None) -> TableCreatePlanApplyState: ...
    def cancel_job(self, id: str, /) -> None: ...
    def create_branch(self, /, branch: str | Branch, from_ref: str | Ref, *, if_not_exists: bool = False) -> Branch: ...
    def create_external_table_from_metadata(self, /, table: str | Table, metadata_json_uri: str, *, namespace: str | Namespace, branch: str | Branch | None = None, overwrite: bool = False) -> Table: ...
    def create_external_table_from_parquet(self, /, table: str | Table, search_patterns: list[str], *, branch: str | Branch | None = None, namespace: str | Namespace | None = None, overwrite: bool = False, args: dict[str, str] | None = None, priority: int | None = None, client_timeout: int | None = None, detach: bool = False) -> ExternalTableCreateState: ...
    def create_namespace(self, /, namespace: str | Namespace, branch: str | Branch, *, commit_body: str | None = None, commit_properties: dict[str, str] | None = None, if_not_exists: bool = False) -> Namespace: ...
    def create_table(self, /, table: str | Table, search_uri: str, *, branch: str | Branch | None = None, namespace: str | Namespace | None = None, partitioned_by: str | None = None, replace: bool | None = None, args: dict[str, str] | None = None, priority: int | None = None, client_timeout: int | None = None) -> Table: ...
    def create_tag(self, /, tag: str | Tag, from_ref: str | Ref, *, if_not_exists: bool = False) -> Tag: ...
    def delete_branch(self, /, branch: str | Branch, *, if_exists: bool = False) -> bool: ...
    def delete_namespace(self, /, namespace: str | Namespace, branch: str | Branch, *, if_exists: bool = False, commit_body: str | None = None, commit_properties: dict[str, str] | None = None) -> Branch: ...
    def delete_table(self, /, table: str | Table, branch: str | Branch, *, namespace: str | None = None, if_exists: bool = False, commit_body: str | None = None, commit_properties: dict[str, str] | None = None) -> Branch: ...
    def delete_tag(self, /, tag: str | Tag, *, if_exists: bool = False) -> bool: ...
    def get_branch(self, /, branch: str | Branch) -> Branch: ...
    def get_branches(self, /, *, name: str | None = None, user: str | None = None, limit: int | None = None) -> typing.Iterator[Branch]: ...
    def get_commits(self, /, ref: str | Ref, *, filter_by_message: str | None = None, filter_by_author_username: str | None = None, filter_by_author_name: str | None = None, filter_by_author_email: str | None = None, filter_by_authored_date: str | None = None, filter_by_authored_date_start_at: str | None = None, filter_by_authored_date_end_at: str | None = None, filter_by_parent_hash: str | None = None, filter_by_properties: dict[str, str] | None = None, filter_: str | None = None, limit: int | None = None) -> typing.Iterator[Commit]: ...
    def get_job(self, job_id: str, /) -> Job: ...
    def get_job_context(self, /, job: str | Job, *, include_logs: bool | None = None, include_snapshot: bool | None = None) -> JobContext: ...
    def get_job_contexts(self, /, jobs: str | list[str] | list[Job], *, include_logs: bool | None = None, include_snapshot: bool | None = None) -> list[JobContext]: ...
    def get_jobs(self, /, *, all_users: bool | None = None, filter_by_ids: str | list[str] | list[Job] | None = None, filter_by_users: str | list[str] | None = None, filter_by_kinds: str | JobKind | list[str] | list[JobKind] | None = None, filter_by_statuses: str | JobState | list[str] | list[JobState] | None = None, filter_by_created_after: datetime.datetime | None = None, filter_by_created_before: datetime.datetime | None = None, limit: int | None = None) -> typing.Iterator[Job]: ...
    def get_logs(self, /, job: str | Job) -> JobLogList: ...
    def get_namespace(self, /, namespace: str | Namespace, ref: str | Ref) -> Namespace: ...
    def get_namespaces(self, /, ref: str | Ref, *, filter_by_name: str | None = None, limit: int | None = None) -> typing.Iterator[Namespace]: ...
    def get_table(self, /, table: str | Table, ref: str | Ref, *, namespace: str | None = None) -> Table: ...
    def get_tables(self, /, ref: str | Ref, *, filter_by_name: str | None = None, filter_by_namespace: str | None = None, limit: int | None = None) -> typing.Iterator[Table]: ...
    def get_tag(self, /, tag: str | Tag) -> Tag: ...
    def get_tags(self, /, *, filter_by_name: str | None = None, limit: int | None = None) -> typing.Iterator[Tag]: ...
    def has_branch(self, /, branch: str | Branch) -> bool: ...
    def has_namespace(self, /, namespace: str | Namespace, ref: str | Ref) -> bool: ...
    def has_table(self, /, table: str | Table, ref: str | Ref, *, namespace: str | None = None) -> bool: ...
    def has_tag(self, /, tag: str | Tag) -> bool: ...
    def import_data(self, /, table: str | Table, search_uri: str, *, branch: str | Branch | None = None, namespace: str | Namespace | None = None, continue_on_error: bool = False, import_duplicate_files: bool = False, best_effort: bool = False, preview: str | None = None, args: dict[str, str] | None = None, priority: int | None = None, client_timeout: int | None = None, detach: bool = False) -> TableDataImportState: ...
    def info(self, /, *, client_timeout: int | None = None) -> InfoState: ...
    def merge_branch(self, /, source_ref: str | Ref, into_branch: str | Branch, *, commit_message: str | None = None, commit_body: str | None = None, commit_properties: dict[str, str] | None = None) -> Branch: ...
    def plan_table_creation(self, /, table: str | Table, search_uri: str, *, branch: str | Branch | None = None, namespace: str | Namespace | None = None, partitioned_by: str | None = None, replace: bool | None = None, args: dict[str, str] | None = None, priority: int | None = None, client_timeout: int | None = None) -> TableCreationPlanState: ...
    def query(self, /, query: str, *, ref: str | Ref | None = None, max_rows: int | None = None, cache: str | None = None, namespace: str | None = None, args: dict[str, str] | None = None, priority: int | None = None, client_timeout: int | None = None) -> pyarrow.Table: ...
    def query_to_csv_file(self, /, path: str, query: str, *, ref: str | Ref | None = None, max_rows: int | None = None, cache: str | None = None, namespace: str | None = None, args: dict[str, str] | None = None, priority: int | None = None, client_timeout: int | None = None) -> str: ...
    def query_to_generator(self, /, query: str, *, ref: str | Ref | None = None, max_rows: int | None = None, cache: str | None = None, namespace: str | None = None, args: dict[str, str] | None = None, priority: int | None = None, client_timeout: int | None = None) -> typing.Iterator[dict[str, typing.Any]]: ...
    def query_to_json_file(self, /, path: str, query: str, *, file_format: str | None = None, ref: str | Ref | None = None, max_rows: int | None = None, cache: str | None = None, namespace: str | None = None, args: dict[str, str] | None = None, priority: int | None = None, client_timeout: int | None = None) -> str: ...
    def query_to_parquet_file(self, /, path: str, query: str, *, ref: str | Ref | None = None, max_rows: int | None = None, cache: str | None = None, namespace: str | None = None, args: dict[str, str] | None = None, priority: int | None = None, client_timeout: int | None = None) -> str: ...
    def rename_branch(self, /, branch: str | Branch, new_branch: str | Branch) -> Branch: ...
    def rename_tag(self, /, tag: str | Tag, new_tag: str | Tag) -> Tag: ...
    def revert_table(self, /, table: str | Table, *, namespace: str | None = None, source_ref: str | Ref, into_branch: str | Branch, replace: bool | None = None, commit_body: str | None = None, commit_properties: dict[str, str] | None = None) -> Branch: ...
    def run(self, /, project_dir: str, *, ref: str | Ref | None = None, namespace: str | Namespace | None = None, parameters: dict[str, str | int | float | bool | None] | None = None, cache: str | None = None, transaction: str | None = None, dry_run: bool | None = None, strict: str | None = None, preview: str | None = None, args: dict[str, str] | None = None, priority: int | None = None, client_timeout: int | None = None, detach: bool | None = None) -> RunState: ...
    def scan(self, /, table: str | Table, *, ref: str | Ref | None = None, columns: list[str] | None = None, filters: str | None = None, limit: int | None = None, cache: str | None = None, namespace: str | Namespace | None = None, args: dict[str, str] | None = None, priority: int | None = None, client_timeout: int | None = None) -> pyarrow.Table: ...

class InfoState:
    @property
    def client_version(self, /) -> str: ...
    @property
    def organization(self, /) -> OrganizationInfo | None: ...
    @property
    def runners(self, /) -> list[RunnerNodeInfo]: ...
    @property
    def user(self, /) -> UserInfo | None: ...

class OrganizationInfo:
    @property
    def default_parameter_secret_key(self, /) -> str | None: ...
    @property
    def default_parameter_secret_public_key(self, /) -> str | None: ...
    @property
    def id(self, /) -> str: ...
    @property
    def name(self, /) -> str: ...
    @property
    def slug(self, /) -> str: ...

class RunnerNodeInfo:
    @property
    def hostname(self, /) -> str: ...

class UserInfo:
    @property
    def first_name(self, /) -> str: ...
    @property
    def full_name(self, /) -> str: ...
    @property
    def id(self, /) -> str: ...
    @property
    def last_name(self, /) -> str: ...
    @property
    def username(self, /) -> str: ...
