import _typeshed

class BauplanHTTPError:
    @property
    def code(self, /) -> int: ...
    @property
    def message(self, /) -> str: ...
    @property
    def type(self, /) -> str: ...

def __getattr__(name: str) -> _typeshed.Incomplete: ...
