import typing

class BauplanError(Exception): ...

class BauplanHTTPError(BauplanError):
    def __new__(cls, /, code: int, type: str, message: str) -> typing.Self: ...
    @property
    def code(self, /) -> int: ...
    @property
    def message(self, /) -> str: ...
    @property
    def type(self, /) -> str: ...

# 400 Bad Request
class BadRequestError(BauplanHTTPError): ...
class InvalidDataError(BadRequestError): ...
class InvalidRefError(BadRequestError): ...
class NotABranchRefError(InvalidRefError): ...
class NotATagRefError(InvalidRefError): ...
class NotAWriteBranchRefError(NotABranchRefError): ...
class SameRefError(InvalidRefError): ...

# 401 Unauthorized
class UnauthorizedError(BauplanHTTPError): ...

# 403 Forbidden
class ForbiddenError(BauplanHTTPError): ...
class AccessDeniedError(BauplanHTTPError): ...
class CreateBranchForbiddenError(ForbiddenError): ...
class CreateNamespaceForbiddenError(ForbiddenError): ...
class CreateTagForbiddenError(ForbiddenError): ...
class DeleteBranchForbiddenError(ForbiddenError): ...
class DeleteNamespaceForbiddenError(ForbiddenError): ...
class DeleteTableForbiddenError(ForbiddenError): ...
class DeleteTagForbiddenError(ForbiddenError): ...
class MergeForbiddenError(ForbiddenError): ...
class RenameBranchForbiddenError(ForbiddenError): ...
class RenameTagForbiddenError(ForbiddenError): ...
class RevertTableForbiddenError(ForbiddenError): ...

# 404 Not Found
class NotFoundError(BauplanHTTPError): ...
class ResourceNotFoundError(NotFoundError): ...
class BranchNotFoundError(ResourceNotFoundError): ...
class NamespaceNotFoundError(ResourceNotFoundError): ...
class RefNotFoundError(ResourceNotFoundError): ...
class TableNotFoundError(ResourceNotFoundError): ...
class TagNotFoundError(ResourceNotFoundError): ...
class ApiMethodError(ResourceNotFoundError): ...

# 405 Method Not Allowed
class MethodNotAllowedError(BauplanHTTPError): ...
class ApiRouteError(MethodNotAllowedError): ...

# 409 Conflict
class ConflictError(BauplanHTTPError): ...
class NamespaceUnresolvedError(ConflictError): ...
class UpdateConflictError(ConflictError): ...
class BranchExistsError(UpdateConflictError): ...
class BranchHeadChangedError(UpdateConflictError): ...
class MergeConflictError(UpdateConflictError): ...
class NamespaceExistsError(UpdateConflictError): ...
class NamespaceIsNotEmptyError(UpdateConflictError): ...
class RevertDestinationTableExistsError(UpdateConflictError): ...
class RevertIdenticalTableError(UpdateConflictError): ...
class TagExistsError(UpdateConflictError): ...

# 429 Too Many Requests
class TooManyRequestsError(BauplanHTTPError): ...

# 5xx Server Errors
class InternalError(BauplanHTTPError): ...
class BadGatewayError(BauplanHTTPError): ...
class ServiceUnavailableError(BauplanHTTPError): ...
class GatewayTimeoutError(BauplanHTTPError): ...

# Non-HTTP errors
class BauplanJobError(BauplanError): ...
class BauplanQueryError(BauplanJobError): ...
class NoResultsFoundError(BauplanError): ...
class InvalidPlanError(BauplanError): ...
