import _typeshed
import typing

class BauplanHTTPError:
    def __new__(cls, /, code: int, type: str, message: str) -> typing.Self: ...
    @property
    def code(self, /) -> int: ...
    @property
    def message(self, /) -> str: ...
    @property
    def type(self, /) -> str: ...

def __getattr__(name: str) -> _typeshed.Incomplete: ...
