import datetime

class Actor:
    @property
    def email(self, /) -> str | None: ...
    @property
    def name(self, /) -> str: ...

class Ref:
    def __str__(self, /) -> str: ...
    @property
    def hash(self, /) -> str: ...
    @property
    def name(self, /) -> str: ...
    @property
    def type(self, /) -> RefType: ...

class Branch(Ref): ...
class Tag(Ref): ...
class DetachedRef(Ref): ...

class RefType:
    BRANCH: RefType
    TAG: RefType
    DETACHED: RefType
    def __eq__(self, /, other: object) -> bool: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __str__(self, /) -> str: ...

class Namespace:
    @property
    def name(self, /) -> str: ...

class TableField:
    @property
    def id(self, /) -> int: ...
    @property
    def name(self, /) -> str: ...
    @property
    def required(self, /) -> bool: ...
    @property
    def type(self, /) -> str: ...

class PartitionField:
    @property
    def name(self, /) -> str: ...
    @property
    def transform(self, /) -> str: ...

class TableKind:
    def __eq__(self, /, other: object) -> bool: ...
    def __ne__(self, /, other: object) -> bool: ...

class Table:
    @property
    def current_schema_id(self, /) -> int | None: ...
    @property
    def current_snapshot_id(self, /) -> int | None: ...
    @property
    def fields(self, /) -> list[TableField]: ...
    @property
    def id(self, /) -> str: ...
    @property
    def kind(self, /) -> TableKind: ...
    @property
    def last_updated_at(self, /) -> datetime.datetime: ...
    @property
    def metadata_location(self, /) -> str: ...
    @property
    def name(self, /) -> str: ...
    @property
    def namespace(self, /) -> str: ...
    @property
    def partitions(self, /) -> list[PartitionField]: ...
    @property
    def properties(self, /) -> dict[str, str]: ...
    @property
    def records(self, /) -> int | None: ...
    @property
    def size(self, /) -> int | None: ...
    @property
    def snapshots(self, /) -> int | None: ...

class Commit:
    @property
    def authored_date(self, /) -> datetime.datetime: ...
    @property
    def authors(self, /) -> list[Actor]: ...
    @property
    def catalog_ref(self, /) -> Ref: ...
    @property
    def committed_date(self, /) -> datetime.datetime: ...
    @property
    def committer(self, /) -> Actor: ...
    @property
    def message(self, /) -> str | None: ...
    @property
    def parent_hashes(self, /) -> list[str]: ...
    @property
    def parent_ref(self, /) -> Ref: ...
    @property
    def properties(self, /) -> dict[str, str]: ...
    @property
    def signed_off_by(self, /) -> list[Actor]: ...

class DAGNode:
    @property
    def id(self, /) -> str: ...
    @property
    def name(self, /) -> str: ...

class DAGEdge:
    @property
    def destination_model(self, /) -> str: ...
    @property
    def source_model(self, /) -> str | None: ...

class JobState:
    UNSPECIFIED: JobState
    NOT_STARTED: JobState
    RUNNING: JobState
    COMPLETE: JobState
    ABORT: JobState
    FAIL: JobState
    OTHER: JobState
    def __eq__(self, /, other: object) -> bool: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __str__(self, /) -> str: ...

class JobKind:
    UNSPECIFIED: JobKind
    RUN: JobKind
    QUERY: JobKind
    IMPORT_PLAN_CREATE: JobKind
    IMPORT_PLAN_APPLY: JobKind
    TABLE_PLAN_CREATE: JobKind
    TABLE_PLAN_CREATE_APPLY: JobKind
    TABLE_IMPORT: JobKind
    def __eq__(self, /, other: object) -> bool: ...
    def __ne__(self, /, other: object) -> bool: ...
    def __str__(self, /) -> str: ...

class Job:
    @property
    def created_at(self, /) -> datetime.datetime | None: ...
    @property
    def finished_at(self, /) -> datetime.datetime | None: ...
    @property
    def id(self, /) -> str: ...
    @property
    def kind(self, /) -> str: ...
    @property
    def kind_type(self, /) -> JobKind: ...
    @property
    def runner(self, /) -> str: ...
    @property
    def started_at(self, /) -> datetime.datetime | None: ...
    @property
    def status(self, /) -> str: ...
    @property
    def status_type(self, /) -> JobState: ...
    @property
    def user(self, /) -> str: ...

class JobLogStream:
    STDOUT: JobLogStream
    STDERR: JobLogStream
    def __eq__(self, /, other: object) -> bool: ...
    def __ne__(self, /, other: object) -> bool: ...

class JobLogLevel:
    ERROR: JobLogLevel
    WARN: JobLogLevel
    DEBUG: JobLogLevel
    INFO: JobLogLevel
    TRACE: JobLogLevel
    def __eq__(self, /, other: object) -> bool: ...
    def __ne__(self, /, other: object) -> bool: ...

class JobLogEvent:
    @property
    def level(self, /) -> JobLogLevel: ...
    @property
    def message(self, /) -> str: ...
    @property
    def stream(self, /) -> JobLogStream: ...

class JobLogList:
    @property
    def events(self, /) -> list[JobLogEvent]: ...
    @property
    def log_events(self, /) -> list[JobLogEvent]: ...

class JobContext:
    @property
    def dag_edges(self, /) -> list[DAGEdge]: ...
    @property
    def dag_nodes(self, /) -> list[DAGNode]: ...
    @property
    def id(self, /) -> str: ...
    @property
    def logs(self, /) -> list[JobLogEvent]: ...
    @property
    def project_id(self, /) -> str | None: ...
    @property
    def project_name(self, /) -> str | None: ...
    @property
    def ref(self, /) -> str | None: ...
    @property
    def snapshot_dict(self, /) -> dict[str, str]: ...
    @property
    def tx_ref(self, /) -> str | None: ...
