import datetime

from bauplan._internal.schema import JobLogEvent

class RunExecutionContext:
    @property
    def cache(self, /) -> str: ...
    @property
    def debug(self, /) -> bool: ...
    @property
    def detach(self, /) -> bool: ...
    @property
    def dry_run(self, /) -> bool: ...
    @property
    def namespace(self, /) -> str: ...
    @property
    def preview(self, /) -> str: ...
    @property
    def project_dir(self, /) -> str: ...
    @property
    def ref(self, /) -> str: ...
    @property
    def snapshot_id(self, /) -> str: ...
    @property
    def snapshot_uri(self, /) -> str: ...
    @property
    def strict(self, /) -> str: ...
    @property
    def transaction(self, /) -> str: ...

class RunState:
    @property
    def ctx(self, /) -> RunExecutionContext: ...
    @property
    def duration(self, /) -> float | None: ...
    @property
    def duration_ns(self, /) -> int | None: ...
    @property
    def ended_at_ns(self, /) -> int | None: ...
    @property
    def error(self, /) -> str | None: ...
    @property
    def job_id(self, /) -> str | None: ...
    @property
    def job_status(self, /) -> str | None: ...
    @property
    def started_at_ns(self, /) -> int: ...
    @property
    def tasks_started(self, /) -> dict[str, datetime.datetime]: ...
    @property
    def tasks_stopped(self, /) -> dict[str, datetime.datetime]: ...
    @property
    def user_logs(self, /) -> list[JobLogEvent]: ...

class ExternalTableCreateContext:
    @property
    def branch_name(self, /) -> str: ...
    @property
    def namespace(self, /) -> str: ...
    @property
    def table_name(self, /) -> str: ...

class ExternalTableCreateState:
    @property
    def ctx(self, /) -> ExternalTableCreateContext: ...
    @property
    def error(self, /) -> str | None: ...
    @property
    def job_id(self, /) -> str | None: ...
    @property
    def job_status(self, /) -> str | None: ...

class TableCreatePlanContext:
    @property
    def branch_name(self, /) -> str: ...
    @property
    def namespace(self, /) -> str: ...
    @property
    def search_string(self, /) -> str: ...
    @property
    def table_name(self, /) -> str: ...
    @property
    def table_partitioned_by(self, /) -> str | None: ...
    @property
    def table_replace(self, /) -> bool: ...

class TableCreationPlanState:
    @property
    def can_auto_apply(self, /) -> bool: ...
    @property
    def ctx(self, /) -> TableCreatePlanContext: ...
    @property
    def error(self, /) -> str | None: ...
    @property
    def files_to_be_imported(self, /) -> list[str]: ...
    @property
    def job_id(self, /) -> str | None: ...
    @property
    def job_status(self, /) -> str | None: ...
    @property
    def plan(self, /) -> str | None: ...

class TableCreatePlanApplyState:
    @property
    def error(self, /) -> str | None: ...
    @property
    def job_id(self, /) -> str | None: ...
    @property
    def job_status(self, /) -> str | None: ...

class TableDataImportContext:
    @property
    def best_effort(self, /) -> bool: ...
    @property
    def branch_name(self, /) -> str: ...
    @property
    def continue_on_error(self, /) -> bool: ...
    @property
    def import_duplicate_files(self, /) -> bool: ...
    @property
    def namespace(self, /) -> str: ...
    @property
    def preview(self, /) -> str: ...
    @property
    def search_string(self, /) -> str: ...
    @property
    def table_name(self, /) -> str: ...
    @property
    def transformation_query(self, /) -> str | None: ...

class TableDataImportState:
    @property
    def ctx(self, /) -> TableDataImportContext: ...
    @property
    def error(self, /) -> str | None: ...
    @property
    def job_id(self, /) -> str | None: ...
    @property
    def job_status(self, /) -> str | None: ...
