[tools]
buf = "1"
bun = "1.2.18"
just = "latest"
node = "lts"
"npm:mdx2vast" = "0.3.1"
pinact = "3.9.0"
protoc = "31"
rust = { version = "1.95.0", profile = "default" }
uv = "0.10"
vale = "3.14.1"
zizmor = "1.23.1"
