install:
    bun install

generate:
    uv sync --reinstall-package bauplan
    uv run gen_sdk_reference.py
    bun run generate-llm-docs
    bun run generate-llms-txt
    cargo run --quiet --manifest-path ../Cargo.toml --bin gen-cli-docs > pages/reference/cli.mdx

build out_dir="./build": install generate
    bun run docusaurus build --out-dir "{{ out_dir }}"

serve: install generate
    bun run docusaurus start

clean:
    rm -rf pages/reference
    rm -rf build/
    rm -rf .docusaurus
